services:
  app-csv:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-csv
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: flask run --host=